<nav class="navbar sticky-top navbar-expand-sm bg-white shadow-sm">
    <div class="container-fluid pt-3 pb-2 d-flex align-items-center">
        <a href="/" class="text-dark navbar-brand ms-5 px-5">
            <i class="fa-solid fa-shop"></i>
            <span class="text-dark ms-2 fw-bold fs-3">The</span><span class="text-dark fw-normal fs-3">Shoppers</span>
        </a>
        <div class="input-group border px-2 py-2" style="border-radius: 30px; width: 40%">
            <input type="text" class="form-control border-0" id='searchInput' placeholder="Search" />
            <button class="btn rounded text-dark pe-4" href="#">
                <i class="fa fa-search"></i>
            </button>
        </div>
        <ul class="navbar-nav ">
            <li class="nav-item px-1">
                <a class="nav-link" href="/order">
                    Your Orders
                </a>
            </li>
            <li class="nav-item px-1">
                <a class="nav-link" href="/order/cart"><i class="fa-solid fa-cart-shopping"></i></a>
            </li>
            <li class="nav-item px-1">
                <a class="nav-link" href="/dashboard">Dashboard</a>
            </li>
            <li class="nav-item px-1">
                <a class="btn btn-dark rounded " id='signinBtn' href="/user">Sign In</a>
            </li>
        </ul>
    </div>
</nav>