<head>
    <title>The Shoppers</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" />
    <link href="../public/css/style.css" rel="stylesheet" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src='https://pagination.js.org/dist/2.1.5/pagination.min.js'></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <style>
        .img__wrap {
            position: relative;
        }

        .img__description {
            position: absolute;
            top: 0;
            bottom: 0;
            left: 0;
            right: 0;
            background: rgba(175, 65, 84, 0.72);
            color: #fff;
            visibility: hidden;
            opacity: 0;
            /* transition effect. not necessary */
            transition: opacity .2s, visibility .2s;
        }

        .img__wrap:hover .img__description {
            visibility: visible;
            opacity: 1;
        }
    </style>
</head>