<!-- Php file to display dashboard -->
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Dashboard</title>

    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="../public/assets/css/style.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src='https://pagination.js.org/dist/2.1.5/pagination.min.js'></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
</head>

<body>
    <header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
        <a href="/" class="text-danger navbar-brand ms-5 px-5">
            <i class="fa-solid fa-shop"></i>
            <span class="text-primary ms-2 fw-bold fs-3">The</span><span class="text-primary fw-normal fs-3">Shoppers</span>
        </a>
        <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <h2 class="text-white py-2">
            Admin Dashboard
        </h2>
        <div class="navbar-nav">
            <div class="nav-item text-nowrap">
                <a class="nav-link px-3" href="#" id='signout'>Sign out</a>
            </div>
        </div>
    </header>
    <?php
    include '../app/views/dashboard/components/sidebar.phtml';

    echo ' <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4" id="admin"> ';

    include '../app/views/dashboard/components/users.phtml';
    include '../app/views/dashboard/components/products.phtml';
    include '../app/views/dashboard/components/orders.phtml';
    echo ' </main>     </div>';
    include '../app/views/dashboard/components/userProfile.phtml';
    include '../app/views/dashboard/components/addNewModal.phtml';
    include '../app/views/components/footer.phtml';
    ?>
</body>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src='../public/javascript/dashboard.js'></script>

</html>