<html>

<Head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <title>Cart Page</title>
</Head>

<body>
    <?php include '../app/views/components/header.phtml'; ?>

    <div class="container-fluid">
        <h1 class="text-center text-dark mt-5">Your Cart</h1>
        <div class="table-responsive mt-4 px-5">
            <table class="table table-striped table-sm" id='userTable'>
                <thead>
                    <tr>
                        <th scope="col">product_ID</th>
                        <th scope="col">product_name</th>
                        <th scope="col">price</th>
                        <th scope="col">quantity</th>
                        <th scope="col">total</th>
                        <th scope='col'></th>
                    </tr>
                </thead>
                <tbody class='cartData'>

                </tbody>

            </table>

            <div class="row">
                <a class="btn btn-dark text-white checkOut"> CHECK OUT</a>
            </div>
        </div>

        <?php
        include '../app/views/components/footer.phtml'; ?>
</body>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src='../public/javascript/cart.js'></script>

</html>