<!DOCTYPE html>
<html lang="en">

<head>

    <title>Order Success</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>

</head>

<style>
    .wrapper {
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
    }
</style>

<body>
    <div class="wrapper">
        <h1 class="text-primary mt-5">
            Your order is placed Successfully
        </h1>
        <h3 class="text-success mt-3 ">Thank you for Shopping with us.</h3>

        <a class="btn btn-danger fw-bold p-3 fs-3 mt-5" href="/">

            Continue Shopping

        </a>

    </div>
</body>

</html>